# -*- coding: utf-8 -*-
"""Akshay_Sol

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4MDhGPJdGVtYARJ5TN6mVIGoVbWzL05
"""

!pip install -q pyomo

from pyomo.environ import *

# create a model
model = ConcreteModel()

model.x1 = Var(domain=NonNegativeReals)
model.x2 = Var(domain=NonNegativeReals)
model.x3= Var(domain=NonNegativeReals)

# declare objective
model.profit = Objective(expr = 8.8*model.x1 + 10.2*model.x2 + 3.5*model.x3, sense=maximize)

# declare constraints
model.constraint1 = Constraint(expr=1/4 * model.x1 + 1/6 * model.x2 + 1/8 * model.x3 <= 90)
model.constraint2 = Constraint(expr=1/4 * model.x1 + 1/3 * model.x2 + 1/12 * model.x3 <= 80)

!apt-get install -y -qq glpk-utils

solver = SolverFactory('glpk', executable = '/usr/bin/glpsol')
solver.solve(model)

# display solution
print('\nProfit = ', model.profit())

print('\nDecision Variables')
print('x = ', model.x1())
print('y = ', model.x2())
print('z = ', model.x3())